version: '2'

services:

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: mysql-dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    restart: on-failure

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx-dockerfile
    ports:
      - 8080:80
    volumes:
      - '.:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    restart: on-failure
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: php-dockerfile
    volumes:
      - '.:/usr/src/app'
    restart: on-failure

